environment-type: local
cross-origin:
  origins: ''
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ykea_1
    username: root
    password: 2904
    hikari:
      maximum-pool-size: 2
      connection-timeout: 20000
      minimum-idle: 1
      idle-timeout: 240000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true